CONTRIBUTORS
============

This document contains a list of all contributors to this project. Contributors that submit changes to this project MUST also change this document to identify themselves by adding their name and email address to the CONTRIBUTOR LIST. The CONTRIBUTOR LIST is maintained in alphabetical order.

A contributor who adds themselves to this list indicates their acceptance of the terms of the CONTRIBUTOR AGREEMENT below. There are NO EXCEPTIONS to this rule. If you do not wish to accept the CONTRIBUTOR AGREEMENT, please do not submit any changes.

This CONTRIBUTOR AGREEMENT is based on the Oracle Contributor Agreement and is used under the Creative Commons Attribution-Share Alike 3.0 Unported License. The original agreement and an FAQ can be found at this location: http://www.oracle.com/technetwork/community/oca-486395.html

This document uses the asciidoc format: http://asciidoc.org.


CONTRIBUTOR AGREEMENT
---------------------

This CONTRIBUTOR AGREEMENT applies to any contribution that you make to the WinFsp project (the "project"), and sets out the intellectual property rights you grant to us in the contributed materials. The term “us” shall mean the original author of this project: Bill Zissimopoulos <billziss at navimatics.com>. The term “you” shall mean the persons or entities identified below. If you agree to be bound by these terms, add your name and email address to the CONTRIBUTOR LIST below; this action will constitute signing this CONTRIBUTOR AGREEMENT. These terms and conditions constitute a binding legal agreement.

1. The term 'contribution' or ‘contributed materials’ means any source code, object code, patch, tool, sample, graphic, specification, manual, documentation, or any other material posted or submitted by you to the project.

2. With respect to any worldwide copyrights, or copyright applications and registrations, in your contribution:
* you hereby assign to us joint ownership, and to the extent that such assignment is or becomes invalid, ineffective or unenforceable, you hereby grant to us a perpetual, irrevocable, non-exclusive, worldwide, no-charge, royalty-free, unrestricted license to exercise all rights under those copyrights. This includes, at our option, the right to sublicense these same rights to third parties through multiple levels of sublicensees or other licensing arrangements;
* you agree that each of us can do all things in relation to your contribution as if each of us were the sole owners, and if one of us makes a derivative work of your contribution, the one who makes the derivative work (or has it made) will be the sole owner of that derivative work;
* you agree that you will not assert any moral rights in your contribution against us, our licensees or transferees;
* you agree that we may register a copyright in your contribution and exercise all ownership rights associated with it; and
* you agree that neither of us has any duty to consult with, obtain the consent of, pay or render an accounting to the other for any use or distribution of your contribution.

3. With respect to any patents you own, or that you can license without payment to any third party, you hereby grant to us a perpetual, irrevocable, non-exclusive, worldwide, no-charge, royalty-free license to:
* make, have made, use, sell, offer to sell, import, and otherwise transfer your contribution in whole or in part, alone or in combination with or included in any product, work or materials arising out of the project to which your contribution was submitted, and
* at our option, to sublicense these same rights to third parties through multiple levels of sublicensees or other licensing arrangements.

4. Except as set out above, you keep all right, title, and interest in your contribution. The rights that you grant to us under these terms are effective on the date you first submitted a contribution to us, even if your submission took place before the date you sign these terms. Any contribution we make available under any license will also be made available under a suitable FSF (Free Software Foundation) or OSI (Open Source Initiative) approved license.

5. You covenant, represent, warrant and agree that:
* each contribution that you submit is and shall be an original work of authorship and you can legally grant the rights set out in this CONTRIBUTOR AGREEMENT;
* to the best of your knowledge, each contribution will not violate any third party's copyrights, trademarks, patents, or other intellectual property rights; and
* each contribution shall be in compliance with U.S. export control laws and other applicable export and import laws.
* You agree to notify us if you become aware of any circumstance which would make any of the foregoing representations inaccurate in any respect.

6. This CONTRIBUTOR AGREEMENT is governed by the laws of the State of Washington and applicable U.S. Federal law. Any choice of law rules will not apply.

7. Please add your name and email address in the CONTRIBUTOR LIST below:
* Either "I am signing on behalf of myself as an individual and no other person or entity, including my employer, has or will have rights with respect my contributions". In this case add your name using the following format:
+
----
|First Last                             |name at example.com
----
* Or "I am signing on behalf of my employer or a legal entity and I have the actual authority to contractually bind that entity". In this case add your name using the following format:
+
----
|First Last (Company and/or URL)        |name at example.com
----


CONTRIBUTOR LIST
----------------
|===
|Alberto Alonso                                                 |alberto at alonso.xyz
|Ben Rubson                                                     |ben.rubson at gmail.com
|Bill Zissimopoulos                                             |billziss at navimatics.com
|Brett Dutro                                                    |brett.dutro at gmail.com
|Colin Atkinson (Atakama, https://atakama.com)                  |colin at atakama.com
|Felix Croes                                                    |felix at dworkin.nl
|Francois Karam (KS2, http://www.ks2.fr)                        |francois.karam at ks2.fr
|Fritz Elfert                                                   |fritz-github at fritz-elfert.de
|Gal Hammer (Red Hat, https://www.redhat.com)                   |ghammer at redhat.com
|John Oberschelp                                                |john at oberschelp.net
|John Tyner                                                     |jtyner at gmail.com
|Paweł Wegner (Google LLC, https://google.com)                  |lemourin at google.com
|Pedro Frejo (Arpa System, https://arpasystem.com)              |pedro.frejo at arpasystem.com
|Sam Kelly (DuroSoft Technologies LLC, https://durosoft.com)    |sam at durosoft.com
|Santiago Ganis                                                 |sganis at gmail.com
|Tobias Urlaub                                                  |saibotu at outlook.de
|Victor Gao                                                     |victgm at outlook.com
|===
